server:
  port: 9002

spring:
  datasource:
    url: jdbc:h2:file:./users
    driver-class-name: org.h2.Driver
    username: root
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true